# Generated by Django 4.2.25 on 2025-10-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_directory_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='profile',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
